### ISSUE TITLE
Add an example/vignette?

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/rwfs#2]
Hi!

I've tried to use the package, but I can't understand how to use it. Can you put up some example code?

**Comment by statguy** [comment]
Hi,

I admit I haven't had time for a proper documentation yet. If I give brief instructions here: So the idea is to inherit *Request (in [WFSRequest.R](https://github.com/rOpenGov/rwfs/blob/master/R/WFSRequest.R) file) and *Client (in [WFSClient.R](https://github.com/rOpenGov/rwfs/blob/master/R/WFSClient.R)) R6 classes. Let's say you want to stream the results from a service, so then inherit WFSStreamingRequest and you need to implement getDataSource abstract method, that returns the full query URL to the service. There are already the methods getCapabilities and getFeature for the standard WFS queries and you can add more for user convenience. To get the list of layers and the layers, feed the request object (that generates the URL) to the client object (WFSStreamingClient). In fact, you might not necessarily need to extend the client class.

You can find an example for WFS 1.x in the [gisfin](https://github.com/rOpenGov/gisfin) package in file [GeoStatFi.R](https://github.com/rOpenGov/gisfin/blob/master/R/GeoStatFi.R) and for WFS 2.x in the [fmi](https://github.com/rOpenGov/fmi) package in [FMIWFSRequest.R](https://github.com/rOpenGov/fmi/blob/master/R/FMIWFSRequest.R) and [FMIWFSClient.R](https://github.com/rOpenGov/fmi/blob/master/R/FMIWFSClient.R) files. The WFS 2.x case is a little bit more complicated as the layers might need to be saved to a file first (due to insufficient support in rgdal) and therefore the fmi package extends the \*Caching\* classes.

HTH

**Comment by MansMeg** [comment]
Thanks! I guess it would be great to put this info in the readme or wiki + link in readme. I guess Im not the only one thinking about this. =)

**Comment by statguy** [comment]
Now with some documentation
