### ISSUE TITLE
Build CRAN files in rwfs/inst/extras/

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/rwfs#6]
@antagomir : What's the story behind `rwfs/inst/extras/build.cran.sh` and `rwfs/inst/extras/document.R`?

**Comment by antagomir** [comment]
Ah, I have used document.R to generate roxygen docs (when not using RStudio), and build.cran.sh to run CMD build/check with the CRAN option. This checks more than the standard build/check in the devtools package or RStudio, and it captures notes/warnings/errors that must be fixed before CRAN submission. It has been just faster to run a single command ./build.cran.sh rather than run all these commands separately & manually each time. Anyway, these can be removed if you like. I can then just have them locally if I need to.

**Comment by jlehtoma** [comment]
Thanks for the explanation, just wanted to check if they have something to do with the actual CRAN services. Sounds useful, no need to remove them on my behalf.
